app:
  host: 127.0.0.1:8888
  name: open-gateway
  register: nacos
  weight: 0
  web_path: /Users/icefox/Documents/nacos/opengateway-macos/web
registry:
  register: nacos
  registry_address:
    - 127.0.0.1:8848
  username: "nacos"
  password: "nacos"
  register_type: interface
  wrap_resp: "true"
  retries: "0"
  request_timeout: "5000"
mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/fps_pay?charset=utf8mb4&parseTime=True&loc=Local"
nacos:
  address:
    - 127.0.0.1:8848
  username: "nacos"
  password: "nacos"
consul:
  address:
    - 127.0.0.1:8500
  token: ""
  schema: "http"
zookeeper:
  address:
    - 127.0.0.1:2181
  username: ""
  password: ""
redis:
  address: "127.0.0.1:6379"
  username: ""
  password: ""
  db: 0
logger:
  filename: "./logs/fps-open-gateway.log"
  max_size: 1
  max_backups: 5
  max_age: 30
  encoding: console