POST http://127.0.0.1:8888/api/json
Content-Type: application/json

{
    "encryptType": "11",
    "filename": "FPS_MANAGER_CONFREFRESH_REQ_990102_20240813164335632.json",
    "sign": "1",
    "signType": "1",
    "bizContent": "1",
    "timestamp": "2024-08-13T16:43:35",
    "version": "2.0"
}
###
POST http://127.0.0.1:8888/api/json
Content-Type: application/json

{
"encryptType": "11",
"filename": "FPS_MANAGER_CONFREFRESH_REQ_990102_20240813164335632.json",
"sign": "1",
"signType": "1",
"bizContent": "1",
"timestamp": "2024-08-13T16:43:35",
"version": "2.0"
}


###
POST http://127.0.0.1:8888/api/json
Content-Type: application/json

{
  "bizContent": "{\"confType\": \"BANK_TEST\",\"confContent\": \"TEST|20240930\"}",
  "encryptType": "NONE",
  "filename": "FPS_MANAGER_CONFREFRESH_REQ_990102_20240813164335632.json",
  "sign": "",
  "signType": "NONE",
  "timestamp": "2024-08-13T16:43:35",
  "version": "2.0"
}

###
POST http://127.0.0.1:8888/api/json
Content-Type: application/json

{
  "bizContent":  "{\"confType\": \"BANK_TEST\",\"confContent\": \"TEST|20240930\",\"user\":{\"confType\": \"BANK_TEST\",\"confContent\": \"TEST|20240930\"}}",
  "encryptType": "NONE",
  "filename": "FPS_MANAGER_CONFREFRESH_REQ_990102_20240813164335632.json",
  "sign": "",
  "signType": "NONE",
  "timestamp": "2024-08-13T16:43:35",
  "version": "2.0"
}
###

###
GET http://127.0.0.1:8888/generic
###
GET http://127.0.0.1:8888/getGatewayChannelConfig

###
GET http://127.0.0.1:8888/getGatewaySystemConfig
